sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- pypy
install:
- pip install pytest
- pip install pytest-rerunfailures
- pip install requests
- pip install coveralls
script:
- coverage run --source=travispy setup.py test
after_success:
- coveralls
